// /etc/named.conf
// Configuração do servidor DNS (BIND) - CentOS 7

options {
    listen-on port 53 { 192.168.8.1; };
    directory       "/var/named";
    allow-query     { localhost; 192.168.8.0/24; };
    recursion yes;
};

zone "manuel.local" IN {
    type master;
    file "named.manuel.local";
    allow-update { none; };
};

zone "8.168.192.in-addr.arpa" IN {
    type master;
    file "named.reverse";
    allow-update { none; };
};
