# /etc/samba/smb.conf
# Configuração do servidor Samba (SMB) - CentOS 7

[global]
   workgroup = WORKGROUP
   server string = Samba Server ASL
   security = user
   map to guest = never

[manuelengrola]
   path = /home/samba/manuelengrola
   valid users = manuelengrola
   read only = no
   browsable = yes
   create mask = 0770
   directory mask = 0770
